### ISSUE TITLE
Notebooks not visible or able to be created

### ISSUE THREAD

**Issue by jterlizzi** [notable/notable#1032]
Hi, 

I just downloaded the latest version of notable. Pretty excited to use it and move away from Evernote. However, I'm not seeing the ability to create Notebooks. Notebooks are vital to my workflow, hoping I just missed something. 

-Jason

**Comment by razlupercio** [comment]
Hey Jason,

the notebook functionality on notable is through tags. More info could be found on this issue: [#54](https://github.com/notable/notable/issues/54l)

**Comment by fabiospampinato** [comment]
@jterlizzi Read page 9 of the [tutorial](https://notable.md/static/pdfs/tutorial/1.8.3.pdf), the one about tags. Notebooks in Notable are just tags, and they don't exist on their own, they exist if there are notes put into them/tagged with them.

---

@razlupercio Your link seems broken.

**Comment by fabiospampinato** [comment]
How can we improve notebooks discoverability? One shouldn't have to read a tutorial to use them.

I have a few ideas:

- [ ] Always provide "Notebooks/" as an autocomplete option for tags #20.
- [ ] Add a context menu option for creating a new notebook #480
  - If there are no notebooks though what would one have to right-click to display this?
- [ ] Add a context menu submenu for adding a note to a tag/notebook #1033
- [ ] Add a command palette command for inserting the current note in a new notebook #338 

If anybody has any other ideas I'm all ears.

This could be made more discoverable just by always showing the "Notebooks" section in the sidebar, but if one doesn't use notebooks at all this would be pretty useless. I'm more in favor  of not cluttering the UI unless necessary.

**Comment by jterlizzi** [comment]
@fabiospampinato  - Thanks for the info. I use Notebooks in the GTD method. You could have a show/hide feature in the sidebar. My vote would be for  420. 

Thanks again, I'm new to the world of open-source.
