### ISSUE TITLE
Reduce heavy dependencies

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#323]
### Feature description

Currently we have a few heavy dependencies, they either increase the size of the bundle significantly or slow things down considerably. 

We should work on making sure these bottlenecks are eliminated, either by submitting a few performance-focused PRs, finding some more performant replacements or rewriting them:

- [x] [enex-dump](https://github.com/fabiospampinato/enex-dump) -> [**Caporal.js**](https://github.com/mattallty/Caporal.js) -> [**tabtab**](https://github.com/mklabs/tabtab): tabtab adds multiple megabytes to the bundle for something we don't even use. Caporal starts up pretty slowly (which is more important for my other CLI apps really, but still) and is not performance-focused in general. Caporal.js should probably be rewritten preserving backwards compatibility as much as possible. Related issues: https://github.com/mklabs/tabtab/issues/48 https://github.com/mattallty/Caporal.js/issues/129.
- [x] [enex-dump](https://github.com/fabiospampinato/enex-dump) -> [**turndown**](https://github.com/domchristie/turndown) -> [**jsdom**](https://github.com/jsdom/jsdom): turndown adds multiple megabytes to the bundle and it takes half a second to import it. I think mainly because it requires jsdom, which we don't really need as we have access to a full browser, and shouldn't probably be used in the first place, there's no need for a DOM implementation for this. jsdom should probably be replaced with a fast xml parser. Related issue: https://github.com/domchristie/turndown/issues/265
- [x] [enex-dump](https://github.com/fabiospampinato/enex-dump) -> **CLI**:
  - We don't need the CLI app provided by this package, maybe we can exclude it entirely via webpack.
  - [**update-notifier**](https://github.com/yeoman/update-notifier): `update-notifier` is fairly heavy on disk, it should probably be slimmed down and/or bundled. Related issue: https://github.com/yeoman/update-notifier/issues/159
  - [**Caporal.js**](https://github.com/mattallty/Caporal.js): `Caporal.js`is too heavy, and slow (which only really matters when using the CLI version of the package), it should be rewritten.
- [x] [overstated](https://github.com/fabiospampinato/overstated) -> [**unstated**](https://github.com/jamiebuilds/unstated): unstated is not great at all for performance when dealing with a monolithic container, that's why I've created overstated, but I think there are some performance benefits to be had when integrating everything into a single package (less wrapper components, skipping re-render logic earlier), currently in Notable about 150 higher-order-components get re-rendered when toggling a checkbox in the preview editor, it's too much. Unstated and overstated's plugins should be integrated into a single package and rewritten with performance in mind. Issues are disabled in unstated's repo so there are no issues to link to :(.
- [x] [**chokidar**](https://github.com/paulmillr/chokidar): it takes a longish time to require it (~150ms), is not very performant and doesn't emit a "rename" event natively. It should be replace with something perhaps more mature such as [`@atom/watcher`](https://github.com/atom/watcher) (the thing they are using in [Atom](https://github.com/atom/atom)). Related issue: https://github.com/atom/watcher/issues/204
- [x] [**remark**](https://github.com/remarkjs/remark): we are using it just for stripping any markdown from titles, which most of the times can be implemented as `_.trimStart ( title, '#' )` really. We should leverage existing dependencies instead of requiring remark.
- [x] [**decompress**](https://www.npmjs.com/package/decompress): we only need to untar the tutorial notes, we don't need all the rest this module provides. We should perhaps replace it with [extract-zip](https://github.com/maxogden/extract-zip).
- [x] [Replace CodeMirror with Monaco](https://github.com/notable/notable/issues/203).
- [x] [Replace showdown with marked](https://github.com/notable/notable/issues/531).
- [x] Remove [electron-localshortcut](https://github.com/parro-it/electron-localshortcut)
- [x] Replace [globby](https://github.com/sindresorhus/globby) with [tiny-glob](https://github.com/terkelg/tiny-glob). Related issue: https://github.com/sindresorhus/globby/issues/50.
- [x] [**mermaid**](https://github.com/knsv/mermaid/issues/843): mermaid requires 39M of stuff to be downloaded. Perhaps we could use the provided bundled version of the library instead, and contribute making the library smaller overall. Related issue: https://github.com/knsv/mermaid/issues/843.

### Feature motivation

Performance is important.
