### ISSUE TITLE
Reduce dependencies futher

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#692]
The less dependencies we have the better, the following optimizations should probably be implemented:

- [x] Remove `crc-32` by removing the `checksum` from notes, we'll use UUIDs anyway in the future #538.
- [x] Use `readdirp` instead of `tiny-glob` as it will be deduplicated since `chokidar` also uses it.
- [x] Rewrite `is-shallow-equal` with support for primitives.
	- [x] use it everywhere it's necessary.
- [x] Remove `prism`, embed a full read-only monaco editor instance instead #719.
- [x] Remove `filenamify`, replace instead with a better library for getting or writing-to an unused filename.
- [x] Rewrite `electron-context-menu`, it has some heavy-ish dependencies for menu entries we never need.
- [x] Rewrite `electron-store`, use our future settings library instead #476.
- [x] Remove `electron-util`.
	- [x] Write a standalone dark mode library.
	- [x] Use a standalone `enforceMacOSAppLocation` module.
- [x] Rewrite `enex-dump`, make it provide some essential APIs only, so that its heavy dependencies are only loaded during development.

**Comment by fabiospampinato** [comment]
I'm closing this as pretty much everything listed as been done, now I "only" have to use inside the app all the core standalone libraries I wrote for it over the past months.
